package com.model;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */

public class TDoc implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String mingcheng;

	private String fujian;

	private String fujianYuanshiming;

	private String del;

	// Constructors

	/** default constructor */
	public TDoc()
	{
	}

	/** full constructor */
	public TDoc(String mingcheng, String fujian, String fujianYuanshiming,
			String del)
	{
		this.mingcheng = mingcheng;
		this.fujian = fujian;
		this.fujianYuanshiming = fujianYuanshiming;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getMingcheng()
	{
		return this.mingcheng;
	}

	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public String getFujianYuanshiming()
	{
		return this.fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}