package com.model;

/**
 * TToudijianli generated by MyEclipse Persistence Tools
 */

public class TToudijianli implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer stuId;

	private Integer zhaopinId;

	private String shijian;

	private String fujian;

	private String fujianYuanshiming;

	private String del;

	// Constructors

	/** default constructor */
	public TToudijianli()
	{
	}

	/** full constructor */
	public TToudijianli(Integer stuId, Integer zhaopinId, String shijian,
			String fujian, String fujianYuanshiming, String del)
	{
		this.stuId = stuId;
		this.zhaopinId = zhaopinId;
		this.shijian = shijian;
		this.fujian = fujian;
		this.fujianYuanshiming = fujianYuanshiming;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getStuId()
	{
		return this.stuId;
	}

	public void setStuId(Integer stuId)
	{
		this.stuId = stuId;
	}

	public Integer getZhaopinId()
	{
		return this.zhaopinId;
	}

	public void setZhaopinId(Integer zhaopinId)
	{
		this.zhaopinId = zhaopinId;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public String getFujianYuanshiming()
	{
		return this.fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}