package com.model;

/**
 * TZhaopinhui generated by MyEclipse Persistence Tools
 */

public class TZhaopinhui implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String mingcheng;

	private String shijian;

	private String didian;

	private String del;

	// Constructors

	/** default constructor */
	public TZhaopinhui()
	{
	}

	/** full constructor */
	public TZhaopinhui(String mingcheng, String shijian, String didian,
			String del)
	{
		this.mingcheng = mingcheng;
		this.shijian = shijian;
		this.didian = didian;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getMingcheng()
	{
		return this.mingcheng;
	}

	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public String getDidian()
	{
		return this.didian;
	}

	public void setDidian(String didian)
	{
		this.didian = didian;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}