package com.model;

/**
 * TZhaopin generated by MyEclipse Persistence Tools
 */

public class TZhaopin implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String zhiwei;

	private String xuliyaoqiu;

	private String daiyui;

	private String gongzuodidian;

	private String gongzuojingyan;

	private String youxiaoqi;

	private String qitashuoming;
	
	private String zhaopinType;
	
	private String fabushijian;

	private Integer userId;
	
	private String del;

	// Constructors

	/** default constructor */
	public TZhaopin()
	{
	}

	/** full constructor */
	public TZhaopin(String zhiwei, String xuliyaoqiu, String daiyui,
			String gongzuodidian, String gongzuojingyan, String youxiaoqi,
			String qitashuoming, Integer userId)
	{
		this.zhiwei = zhiwei;
		this.xuliyaoqiu = xuliyaoqiu;
		this.daiyui = daiyui;
		this.gongzuodidian = gongzuodidian;
		this.gongzuojingyan = gongzuojingyan;
		this.youxiaoqi = youxiaoqi;
		this.qitashuoming = qitashuoming;
		this.userId = userId;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getZhiwei()
	{
		return this.zhiwei;
	}

	public String getFabushijian()
	{
		return fabushijian;
	}

	public void setFabushijian(String fabushijian)
	{
		this.fabushijian = fabushijian;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public void setZhiwei(String zhiwei)
	{
		this.zhiwei = zhiwei;
	}

	public String getXuliyaoqiu()
	{
		return this.xuliyaoqiu;
	}

	public String getZhaopinType()
	{
		return zhaopinType;
	}

	public void setZhaopinType(String zhaopinType)
	{
		this.zhaopinType = zhaopinType;
	}

	public void setXuliyaoqiu(String xuliyaoqiu)
	{
		this.xuliyaoqiu = xuliyaoqiu;
	}

	public String getDaiyui()
	{
		return this.daiyui;
	}

	public void setDaiyui(String daiyui)
	{
		this.daiyui = daiyui;
	}

	public String getGongzuodidian()
	{
		return this.gongzuodidian;
	}

	public void setGongzuodidian(String gongzuodidian)
	{
		this.gongzuodidian = gongzuodidian;
	}

	public String getGongzuojingyan()
	{
		return this.gongzuojingyan;
	}

	public void setGongzuojingyan(String gongzuojingyan)
	{
		this.gongzuojingyan = gongzuojingyan;
	}

	public String getYouxiaoqi()
	{
		return this.youxiaoqi;
	}

	public void setYouxiaoqi(String youxiaoqi)
	{
		this.youxiaoqi = youxiaoqi;
	}

	public String getQitashuoming()
	{
		return this.qitashuoming;
	}

	public void setQitashuoming(String qitashuoming)
	{
		this.qitashuoming = qitashuoming;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

}